ARG BASE_IMAGE
ARG BASE_IMAGE_VERSION

FROM "${BASE_IMAGE}:${BASE_IMAGE_VERSION}"

# TODO: change USER
USER root

# Install vcf2maf, vep, samtools, htslib from github repos (htslib needed first)
RUN apk --update add jq \
        ncurses-dev \
        expat \
        expat-dev \
        libxml2-dev \
        libxslt-dev \
        perl-app-cpanminus \
        perl-dbi \
        perl-dev \
        perl-utils \
        wget && \
    git clone https://github.com/samtools/htslib.git && \
    cd htslib && \
    git submodule update --init --recursive && \
    make && \
    make install && \
    cd .. && \
    git clone https://github.com/samtools/samtools.git && \
    cd samtools && \
    make && \
    make install && \
    cd .. && \
    git clone https://github.com/Ensembl/ensembl-vep.git && \
    # Install perl dependencies for ensembl-vep
    cpanm --installdeps --with-recommends --notest --cpanfile ensembl-vep/cpanfile . && \
    cd ensembl-vep && \
    # Build vep in /ensembl-vep
    perl INSTALL.pl -a a --NO_TEST && \
    cd .. && \
    rm -rf htslib samtools && \
    git clone https://github.com/mskcc/vcf2maf.git && \
    mkdir -p /opt/data && \
    cp vcf2maf/*.pl /opt/ && \
    cp -r vcf2maf/data /opt/data && \
    rm -rf vcf2maf

# Add ensembl-vep to the PATH so that vep can be called from vcf2map script
ENV PATH /ensembl-vep:$PATH

RUN mkdir /wes; \
    # for temp data, shared volume
    mkdir /wes/tmp; \
    # drop-box shared volume
    mkdir /data

WORKDIR /wes

#RUN wget -cO - https://github.com/broadinstitute/cromwell/releases/download/55/womtool-55.jar > womtool.jar

COPY chord_services.json ./chord_services.json

WORKDIR /wes/bento_wes
# Copy the repo requirements.txt and install them
# directly in the container before loading the project
# directory as a volume
COPY ./bento_wes/requirements.txt /wes/bento_wes/requirements.txt

RUN ["pip", "install", "debugpy", "-r", "requirements.txt"]

# Run
WORKDIR /wes

COPY chord_services.json ./chord_services.json
COPY startup.dev.sh ./startup.dev.sh

CMD ["sh", "startup.dev.sh"]
