ARG BASE_IMAGE
ARG BASE_IMAGE_VERSION

FROM "${BASE_IMAGE}:${BASE_IMAGE_VERSION}"

# TODO: change USER
USER root

ENV LIBRARY_PATH=/lib:/usr/lib

WORKDIR /federation

# # Create data directory
RUN mkdir -p /federation/data

ARG REPO
ARG BRANCH
ARG TAG

# Copy from local requirements
COPY ./bento_federation_service/requirements.txt /federation/bento_federation_service/requirements.txt

WORKDIR /federation/bento_federation_service


RUN ["pip", "install", "debugpy", "-r", "requirements.txt"]
