# extends main docker-compose.yml and various service-specific compose files;
# adds in development/debug environment variables, debugpy ports

services:
  web:
    extends:
      file: docker-compose.yaml
      service: web

  public:
    extends:
      file: docker-compose.yaml
      service: public
    networks: 
      - bridge-net
    ports:
      - "${BENTO_PUBLIC_EXTERNAL_PORT}:${BENTO_PUBLIC_INTERNAL_PORT}"

  gateway:
    # Override network aliases, adding BENTOV2_AUTH_DOMAIN
    networks:
        bridge-net:
          aliases:
            - ${BENTOV2_DOMAIN}
            - ${BENTOV2_PORTAL_DOMAIN}
            - ${BENTOV2_AUTH_DOMAIN}
    extends:
      file: docker-compose.yaml
      service: gateway

  katsu:
    networks:
      - bridge-net
    depends_on:
      - katsu-db
    extends:
      file: $PWD/lib/katsu/docker-compose.katsu.yaml
      service: katsu
    volumes:
      - ${BENTOV2_KATSU_DEV_WES_VOL_TMP_DIR}:/wes/tmp:ro
    environment:
      - BENTO_DEBUG=True
      - CHORD_DEBUG=True
      - DEBUGGER_PORT=${BENTOV2_KATSU_DEBUGGER_EXTERNAL_PORT}
    ports:
      - "${BENTOV2_KATSU_EXTERNAL_PORT}:${BENTOV2_KATSU_INTERNAL_PORT}"
      - "${BENTOV2_KATSU_DEBUGGER_EXTERNAL_PORT}:${BENTOV2_KATSU_DEBUGGER_INTERNAL_PORT}"

  katsu-db:
    networks:
      - bridge-net
    extends:
      file: $PWD/lib/katsu/docker-compose.katsu.yaml
      service: katsu-db
    ports:
      - "${BENTOV2_KATSU_DB_EXTERNAL_PORT}:${BENTOV2_KATSU_DB_INTERNAL_PORT}"
    volumes:
      - ${BENTOV2_KATSU_DB_DEV_VOL_DIR}:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1
    networks:
      - bridge-net
    container_name: ${BENTOV2_PREFIX}-katsu-adminer
    restart: unless-stopped
    ports:
      - 8080:8080

  aggregation:
    environment:
      - BENTO_DEBUG=True
      - CHORD_DEBUG=True
      - LOG_LEVEL=debug
      - PORT=${BENTOV2_AGGREGATION_INTERNAL_PORT}
      - DEBUGGER_PORT=${BENTOV2_AGGREGATION_DEBUGGER_INTERNAL_PORT}
    networks:
      - bridge-net
    extends:
      file: $PWD/lib/aggregation/docker-compose.aggregation.yaml
      service: aggregation
    ports:
      - "${BENTOV2_AGGREGATION_EXTERNAL_PORT}:${BENTOV2_AGGREGATION_INTERNAL_PORT}"
      - "${BENTOV2_AGGREGATION_DEBUGGER_EXTERNAL_PORT}:${BENTOV2_AGGREGATION_DEBUGGER_INTERNAL_PORT}"

  wes:
    networks:
      - bridge-net
    environment:
      - BENTO_DEBUG=True
      - CHORD_DEBUG=True
      - FLASK_DEBUG=true
      - DEBUGGER_PORT=${BENTOV2_WES_DEBUGGER_EXTERNAL_PORT}
    extends:
      file: $PWD/lib/wes/docker-compose.wes.yaml
      service: wes
    volumes:
      - ${BENTOV2_WES_DEV_VOL_DIR}:/wes/data
      - ${BENTOV2_WES_DEV_VOL_TMP_DIR}:/wes/tmp
      - ${BENTOV2_WES_DEV_DROP_BOX_VOL_DIR}:/data
    ports:
      - "${BENTOV2_WES_EXTERNAL_PORT}:${BENTOV2_WES_INTERNAL_PORT}"
      - "${BENTOV2_WES_DEBUGGER_EXTERNAL_PORT}:${BENTOV2_WES_DEBUGGER_INTERNAL_PORT}"

  drs:
    environment:
      - FLASK_DEBUG=true
      - DEBUGGER_PORT=${BENTOV2_DRS_DEBUGGER_EXTERNAL_PORT}
    networks:
      - bridge-net
    extends:
      file: $PWD/lib/drs/docker-compose.drs.yaml
      service: drs
    ports:
      - "${BENTOV2_DRS_EXTERNAL_PORT}:5000"
      - "${BENTOV2_DRS_DEBUGGER_EXTERNAL_PORT}:${BENTOV2_DRS_DEBUGGER_INTERNAL_PORT}"
    volumes:
      # Override main drs data directory
      - ${BENTOV2_DRS_DEV_VOL_DIR}:/drs/chord_drs/data

  beacon:
    networks:
      - bridge-net
    environment:
      - BENTO_DEBUG=True
      - CHORD_DEBUG=True
      - BENTO_BEACON_DEBUG=true
      - FLASK_ENV=development
    extends:
      file: $PWD/lib/beacon/docker-compose.beacon.yaml
      service: beacon
    ports:
      - "${BENTO_BEACON_EXTERNAL_PORT}:${BENTO_BEACON_INTERNAL_PORT}"
      - "${BENTO_BEACON_DEBUGGER_EXTERNAL_PORT}:${BENTO_BEACON_DEBUGGER_INTERNAL_PORT}"

  service-registry:
    environment:
      - FLASK_DEBUG=True
      - BENTO_DEBUG=True
    extends:
      file: docker-compose.yaml
      service: service-registry

  drop-box:
    environment:
      # Runtime
      - FLASK_DEBUG=True
      - BENTO_DEBUG=True
    extends:
      file: docker-compose.yaml
      service: drop-box

  notification:
    environment:
      # Runtime
      - FLASK_DEBUG=True
      - BENTO_DEBUG=True
    extends:
      file: docker-compose.yaml
      service: notification

  event-relay:
    environment:
      - NODE_ENV=development
    extends:
      file: docker-compose.yaml
      service: event-relay

networks:
  bridge-net:
    external: true
