# merges with docker-compose.yaml and docker-compose.dev.yaml; adds in repository volumes + git configuration

services:
  web:
    image: ${BENTOV2_WEB_IMAGE}:${BENTOV2_WEB_VERSION_DEV}
    volumes:
      - ./repos/web:/web
      - ./packs:/packs
    environment:
      - BENTO_GIT_NAME
      - BENTO_GIT_EMAIL
      - BENTO_GIT_REPOSITORY_DIR=/web

  public:
    image: ${BENTO_PUBLIC_IMAGE}:${BENTO_PUBLIC_VERSION_DEV}
    volumes:
      - ./repos/public:/bento-public
      - ./packs:/packs
      - ${PWD}/lib/public/en_about.html:/bento-public/src/public/en_about.html
      - ${PWD}/lib/public/fr_about.html:/bento-public/src/public/fr_about.html
      - ${PWD}/lib/public/branding.png:/bento-public/src/public/assets/branding.png
      - ${PWD}/lib/public/branding.lightbg.png:/bento-public/src/public/assets/branding.lightbg.png
      - ${PWD}/lib/public/translations/en.json:/bento-public/src/public/locales/en/translation_en.json
      - ${PWD}/lib/public/translations/fr.json:/bento-public/src/public/locales/fr/translation_fr.json
    environment:
      - BENTO_GIT_NAME
      - BENTO_GIT_EMAIL
      - BENTO_GIT_REPOSITORY_DIR=/bento-public
    profiles:
      - public

  gateway:
    image: ${BENTOV2_GATEWAY_IMAGE}:${BENTOV2_GATEWAY_VERSION_DEV}
    volumes:
      - ./repos/gateway/src:/gateway/src:ro
      - ./repos/gateway/conf:/gateway/conf:ro
    environment:
      - BENTO_GIT_NAME
      - BENTO_GIT_EMAIL
      - BENTO_GIT_REPOSITORY_DIR=/gateway

  authz:
    image: ${BENTO_AUTHZ_IMAGE}:${BENTO_AUTHZ_VERSION_DEV}
    volumes:
      - ./repos/authz:/authorization
    environment:
      - BENTO_GIT_NAME
      - BENTO_GIT_EMAIL
      - BENTO_GIT_REPOSITORY_DIR=/authorization

  katsu:
    image: ${BENTOV2_KATSU_IMAGE}:${BENTOV2_KATSU_VERSION_DEV}
    depends_on:
      - katsu-db
    volumes:
      - ./repos/katsu:/app
      - ${BENTOV2_KATSU_DEV_WES_VOL_TMP_DIR}:/wes/tmp:ro
    environment:
      - BENTO_GIT_NAME
      - BENTO_GIT_EMAIL
      - BENTO_GIT_REPOSITORY_DIR=/app

  aggregation:
    image: ${BENTOV2_AGGREGATION_IMAGE}:${BENTOV2_AGGREGATION_VERSION_DEV}
    environment:
      - BENTO_GIT_NAME
      - BENTO_GIT_EMAIL
      - BENTO_GIT_REPOSITORY_DIR=/aggregation
    volumes:
      - ./repos/aggregation:/aggregation

  wes:
    image: ${BENTOV2_WES_IMAGE}:${BENTOV2_WES_VERSION_DEV}
    environment:
      - BENTO_GIT_NAME
      - BENTO_GIT_EMAIL
      - BENTO_GIT_REPOSITORY_DIR=/wes
      - CELERY_DEBUG=true
    volumes:
      - ./repos/wes:/wes

  drs:
    image: ${BENTOV2_DRS_IMAGE}:${BENTOV2_DRS_VERSION_DEV}
    environment:
      - BENTO_GIT_NAME
      - BENTO_GIT_EMAIL
      - BENTO_GIT_REPOSITORY_DIR=/drs
    volumes:
      - ./repos/drs:/drs

  beacon:
    image: ${BENTO_BEACON_IMAGE}:${BENTO_BEACON_VERSION_DEV}
    environment:
      - BENTO_GIT_NAME
      - BENTO_GIT_EMAIL
      - BENTO_GIT_REPOSITORY_DIR=/beacon
      - DEBUGGER_PORT=${BENTO_BEACON_DEBUGGER_INTERNAL_PORT}
    volumes:
      - ./repos/beacon:/beacon
    profiles:
      - beacon

  service-registry:
    image: ${BENTOV2_SERVICE_REGISTRY_IMAGE}:${BENTOV2_SERVICE_REGISTRY_VERSION_DEV}
    volumes:
      - ./repos/service-registry:/service-registry
      - ./etc/bento_services.json:/bento_services.json:ro
    environment:
      - BENTO_SERVICES=/bento_services.json
      - BENTO_GIT_NAME
      - BENTO_GIT_EMAIL
      - BENTO_GIT_REPOSITORY_DIR=/service_registry

  drop-box:
    image: ${BENTOV2_DROP_BOX_IMAGE}:${BENTOV2_DROP_BOX_VERSION_DEV}
    environment:
      - BENTO_GIT_NAME
      - BENTO_GIT_EMAIL
      - BENTO_GIT_REPOSITORY_DIR=/drop-box
    volumes:
      - ./repos/drop-box:/drop-box

  notification:
    image: ${BENTOV2_NOTIFICATION_IMAGE}:${BENTOV2_NOTIFICATION_VERSION_DEV}
    environment:
      - BENTO_GIT_NAME
      - BENTO_GIT_EMAIL
      - BENTO_GIT_REPOSITORY_DIR=/notification
    volumes:
      - ./repos/notification:/notification

  event-relay:
    image: ${BENTOV2_EVENT_RELAY_IMAGE}:${BENTOV2_EVENT_RELAY_VERSION_DEV}
    environment:
      - BENTO_GIT_NAME
      - BENTO_GIT_EMAIL
      - BENTO_GIT_REPOSITORY_DIR=/app
    volumes:
      - ./repos/event-relay:/app

  reference:
    image: ${BENTO_REFERENCE_IMAGE}:${BENTO_REFERENCE_VERSION_DEV}
    environment:
      - BENTO_GIT_NAME
      - BENTO_GIT_EMAIL
      - BENTO_GIT_REPOSITORY_DIR=/reference
    volumes:
      - ./repos/reference:/reference

  gohan-api:
    image: ${BENTOV2_GOHAN_API_IMAGE}:${BENTOV2_GOHAN_API_VERSION_DEV}
    privileged: true # required to debug golang
    environment:
      - BENTO_GIT_NAME
      - BENTO_GIT_EMAIL
      - BENTO_GIT_REPOSITORY_DIR=/gohan-api
    volumes:
      - ./repos/gohan-api:/gohan-api
      - ./repos/gohan-api/src/api/workflows:/app/workflows
