secrets:
  metadata-app-secret:
    file: $PWD/tmp/secrets/metadata-app-secret
  metadata-db-user:
    file: $PWD/tmp/secrets/metadata-db-user
  metadata-db-secret:
    file: $PWD/tmp/secrets/metadata-db-secret

services:
  web:
    image: ${BENTOV2_WEB_IMAGE}:${BENTOV2_WEB_VERSION_DEV}
    volumes:
      - ./repos/web:/web
    # Execute npm build/install and watch, and
    # nginx "listener" upon container startup
    extends:
      file: docker-compose.yaml
      service: web

  public:
    image: ${BENTO_PUBLIC_IMAGE}:${BENTO_PUBLIC_VERSION_DEV}
    extends:
      file: docker-compose.yaml
      service: public
    networks: 
      - bridge-net
    ports:
      - "${BENTO_PUBLIC_EXTERNAL_PORT}:${BENTO_PUBLIC_INTERNAL_PORT}"

  gateway:
    image: ${BENTOV2_GATEWAY_IMAGE}:${BENTOV2_GATEWAY_VERSION_DEV}
    # Override network aliases, adding BENTOV2_AUTH_DOMAIN
    networks:
        bridge-net:
          aliases:
            - ${BENTOV2_DOMAIN}
            - ${BENTOV2_PORTAL_DOMAIN}
            - ${BENTOV2_AUTH_DOMAIN}
    extends:
      file: docker-compose.yaml
      service: gateway

  katsu:
    image: ${BENTOV2_KATSU_IMAGE}:${BENTOV2_KATSU_VERSION_DEV}
    networks:
      - bridge-net
    depends_on:
      - katsu-db
    extends:
      file: $PWD/lib/katsu/docker-compose.katsu.yaml
      service: katsu
    volumes:
      - ./repos/katsu:/app
      - ${BENTOV2_KATSU_DEV_WES_VOL_TMP_DIR}:/wes/tmp:ro
    environment:
      - BENTO_DEBUG=True
      - CHORD_DEBUG=True
      - DEBUGGER_PORT=${BENTOV2_KATSU_DEBUGGER_EXTERNAL_PORT}
    ports:
      - "${BENTOV2_KATSU_EXTERNAL_PORT}:${BENTOV2_KATSU_INTERNAL_PORT}"
      - "${BENTOV2_KATSU_DEBUGGER_EXTERNAL_PORT}:${BENTOV2_KATSU_DEBUGGER_INTERNAL_PORT}"

  katsu-db:
    networks:
      - bridge-net
    extends:
      file: $PWD/lib/katsu/docker-compose.katsu.yaml
      service: katsu-db
    ports:
      - "${BENTOV2_KATSU_DB_EXTERNAL_PORT}:${BENTOV2_KATSU_DB_INTERNAL_PORT}"
    volumes:
      - ${BENTOV2_KATSU_DB_DEV_VOL_DIR}:/var/lib/postgresql/data


  aggregation:
    image: ${BENTOV2_AGGREGATION_IMAGE}:${BENTOV2_AGGREGATION_VERSION_DEV}
    environment:
      - BENTO_DEBUG=True
      - CHORD_DEBUG=True
      - PORT=${BENTOV2_AGGREGATION_INTERNAL_PORT}
      - DEBUGGER_PORT=${BENTOV2_AGGREGATION_DEBUGGER_INTERNAL_PORT}
    networks:
      - bridge-net
    extends:
      file: $PWD/lib/aggregation/docker-compose.aggregation.yaml
      service: aggregation
    volumes:
      - ./repos/aggregation/bento_aggregation_service:/aggregation/bento_aggregation_service
    ports:
      - "${BENTOV2_AGGREGATION_EXTERNAL_PORT}:${BENTOV2_AGGREGATION_INTERNAL_PORT}"
      - "${BENTOV2_AGGREGATION_DEBUGGER_EXTERNAL_PORT}:${BENTOV2_AGGREGATION_DEBUGGER_INTERNAL_PORT}"

  wes:
    image: ${BENTOV2_WES_IMAGE}:${BENTOV2_WES_VERSION_DEV}
    networks:
      - bridge-net
    environment:
      - BENTO_DEBUG=True
      - CHORD_DEBUG=True
      - FLASK_DEBUG=true
      - DEBUGGER_PORT=${BENTOV2_WES_DEBUGGER_EXTERNAL_PORT}
    extends:
      file: $PWD/lib/wes/docker-compose.wes.yaml
      service: wes
    volumes:
      - ./repos/wes:/wes
      - ${BENTOV2_WES_DEV_VOL_DIR}:/wes/data
      - ${BENTOV2_WES_DEV_VOL_TMP_DIR}:/wes/tmp
      - ${BENTOV2_WES_DEV_DROP_BOX_VOL_DIR}:/data
    ports:
      - "${BENTOV2_WES_EXTERNAL_PORT}:${BENTOV2_WES_INTERNAL_PORT}"
      - "${BENTOV2_WES_DEBUGGER_EXTERNAL_PORT}:${BENTOV2_WES_DEBUGGER_INTERNAL_PORT}"

  drs:
    image: ${BENTOV2_DRS_IMAGE}:pr-36-dev
    environment:
      - FLASK_DEBUG=true
      - DEBUGGER_PORT=${BENTOV2_DRS_DEBUGGER_EXTERNAL_PORT}
    networks:
      - bridge-net
    extends:
      file: $PWD/lib/drs/docker-compose.drs.yaml
      service: drs
    ports:
      - "${BENTOV2_DRS_EXTERNAL_PORT}:5000"
      - "${BENTOV2_DRS_DEBUGGER_EXTERNAL_PORT}:${BENTOV2_DRS_DEBUGGER_INTERNAL_PORT}"
    volumes:
      - ./repos/drs/chord_drs:/drs/chord_drs
      # Override main drs data directory
      - ${BENTOV2_DRS_DEV_VOL_DIR}:/drs/chord_drs/data
      - ${BENTOV2_DRS_DEV_WES_VOL_DIR}:/wes/tmp

  beacon:
    image: ${BENTO_BEACON_IMAGE}:${BENTO_BEACON_VERSION_DEV}
    networks:
      - bridge-net
    environment:
      - BENTO_DEBUG=True
      - CHORD_DEBUG=True
      - BENTO_BEACON_DEBUG=true
      - FLASK_ENV=development
    extends:
      file: $PWD/lib/beacon/docker-compose.beacon.yaml
      service: beacon
    volumes:
      - ./repos/beacon/bento_beacon:/beacon/bento_beacon
      - ./repos/beacon/config:/config
    ports:
      - "${BENTO_BEACON_EXTERNAL_PORT}:${BENTO_BEACON_INTERNAL_PORT}"
      - "${BENTO_BEACON_DEBUGGER_EXTERNAL_PORT}:${BENTO_BEACON_DEBUGGER_INTERNAL_PORT}"

  service-registry:
    image: ${BENTOV2_SERVICE_REGISTRY_IMAGE}:${BENTOV2_SERVICE_REGISTRY_VERSION_DEV}
    volumes:
      - ./repos/service-registry/bento_service_registry:/service-registry/bento_service_registry/
      - ./lib/service-registry/chord_services.json:/service-registry/bento_service_registry/chord_services.json:ro
    environment:
      - FLASK_DEBUG=True
      - BENTO_DEBUG=True
    extends:
      file: docker-compose.yaml
      service: service-registry

  drop-box:
      image: ${BENTOV2_DROP_BOX_IMAGE}:${BENTOV2_DROP_BOX_VERSION_DEV}
      environment:
        # Runtime
        - FLASK_DEBUG=True
        - BENTO_DEBUG=True
      volumes:
        - ./repos/drop-box/bento_drop_box_service:/drop-box/bento_drop_box_service/
      extends:
        file: docker-compose.yaml
        service: drop-box

  notification:
    image: ${BENTOV2_NOTIFICATION_IMAGE}:${BENTOV2_NOTIFICATION_VERSION_DEV}
    environment:
      # Runtime
      - FLASK_DEBUG=True
      - BENTO_DEBUG=True
    volumes:
      - ./repos/notification:/notification
    extends:
      file: docker-compose.yaml
      service: notification

  event-relay:
    image: ${BENTOV2_EVENT_RELAY_IMAGE}:${BENTOV2_EVENT_RELAY_VERSION_DEV}
    environment:
      - NODE_ENV=development
    volumes:
      - ./repos/event-relay:/app
    extends:
      file: docker-compose.yaml
      service: event-relay

networks:
  bridge-net:
    external: true
