version: '3.7'

secrets:
  metadata-app-secret:
    file: $PWD/tmp/secrets/metadata-app-secret
  metadata-db-user:
    file: $PWD/tmp/secrets/metadata-db-user
  metadata-db-secret:
    file: $PWD/tmp/secrets/metadata-db-secret


services:
  ingress:
    build:
      context: $PWD/lib/ingress
      args:
        BASE_IMAGE: ${BENTOV2_INGRESS_BASE_IMAGE}
        BASE_IMAGE_VERSION: ${BENTOV2_INGRESS_BASE_IMAGE_VERSION}
    image: ${BENTOV2_INGRESS_IMAGE}:${BENTOV2_INGRESS_VERSION}
    container_name: ${BENTOV2_INGRESS_CONTAINER_NAME}
    networks: 
      - bridge-net
    ports:
      - "80:80"
      - "443:443"


  web:
    build:
      context: $PWD/lib/web
      args:
        BASE_IMAGE: ${BENTOV2_WEB_BASE_IMAGE}
        BASE_IMAGE_VERSION: ${BENTOV2_WEB_BASE_IMAGE_VERSION}
        BENTO_WEB_REPO: ${BENTO_WEB_REPO}
        BENTO_WEB_BRANCH: ${BENTO_WEB_BRANCH}
    image: ${BENTOV2_WEB_IMAGE}:${BENTOV2_WEB_VERSION}
    container_name: ${BENTOV2_WEB_CONTAINER_NAME}
    networks: 
      - bridge-net
    ports:
       - "${BENTOV2_WEB_EXTERNAL_PORT}:${BENTOV2_WEB_INTERNAL_PORT}"


  katsu:
    build:
      context: $PWD/lib/katsu
      args:
        BASE_IMAGE:  ${BENTOV2_KATSU_BASE_IMAGE}
        BASE_IMAGE_VERSION: ${BENTOV2_KATSU_BASE_IMAGE_VERSION}
        KATSU_REPO: ${KATSU_REPO}
        KATSU_BRANCH: ${KATSU_BRANCH}
        KATSU_TAG: ${KATSU_TAG}
    image: ${BENTOV2_KATSU_IMAGE}:${BENTOV2_KATSU_VERSION}
    container_name: ${BENTOV2_KATSU_CONTAINER_NAME}
    ports:
      - "${BENTOV2_KATSU_EXTERNAL_PORT}:${BENTOV2_KATSU_INTERNAL_PORT}"
    networks: 
      - bridge-net
    depends_on:
      - katsu-db
    environment:
      - CHORD_URL="${CHORD_METADATA_HOST}"
      - CHORD_PERMISSIONS="${CHORD_METADATA_AUTH}"
      - CHORD_DEBUG="${CHORD_METADATA_DEBUG}"
      - POSTGRES_HOST=${BENTOV2_KATSU_DB_CONTAINER_NAME}
      - POSTGRES_USER=${BENTOV2_KATSU_DB_USER}
      - POSTGRES_PASSWORD=${BENTOV2_KATSU_DB_PASSWORD}
    configs:
      - source: chord-metadata-settings
        target: /katsu/metadata/settings.py
        mode: 0644
    secrets:
      - source: metadata-app-secret
        target: metadata_app_secret
      - source: metadata-db-user
        target: metadata_db_user
      - source: metadata-db-secret
        target: metadata_db_secret
    entrypoint:
      - /bin/sh
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:${BENTOV2_KATSU_INTERNAL_PORT}


  katsu-db:
    image: ${BENTOV2_KATSU_DB_IMAGE}:${BENTOV2_KATSU_DB_VERSION}
    container_name: ${BENTOV2_KATSU_DB_CONTAINER_NAME}
    networks: 
      - bridge-net
    environment:
      - POSTGRES_USER=${BENTOV2_KATSU_DB_USER}
      - POSTGRES_PASSWORD=${BENTOV2_KATSU_DB_PASSWORD}
      #- POSTGRES_PASSWORD_FILE="/run/secrets/metadata_db_secret"
      - POSTGRES_DB=${BENTOV2_KATSU_DB}
    # ports: 
    #   - 5432
    secrets:
      - source: metadata-db-user
        target: metadata_db_user
      - source: metadata-db-secret
        target: metadata_db_secret


networks: 
  bridge-net:
    external: true