version: '3.7'

#TODO: volumes

secrets:
  metadata-app-secret:
    file: $PWD/tmp/secrets/metadata-app-secret
  metadata-db-user:
    file: $PWD/tmp/secrets/metadata-db-user
  metadata-db-secret:
    file: $PWD/tmp/secrets/metadata-db-secret


services:
  ingress:
    build:
      context: $PWD/lib/ingress
      args:
        BASE_IMAGE: ${BENTOV2_INGRESS_BASE_IMAGE}
        BASE_IMAGE_VERSION: ${BENTOV2_INGRESS_BASE_IMAGE_VERSION}
    image: ${BENTOV2_INGRESS_IMAGE}:${BENTOV2_INGRESS_VERSION}
    container_name: ${BENTOV2_INGRESS_CONTAINER_NAME}
    networks: 
      bridge-net:
        aliases:
          - bentov2.local
          - bentov2auth.local
    ports:
      - "80:80"
      - "443:443"


  auth:
    image: ${BENTOV2_AUTH_IMAGE}:${BENTOV2_AUTH_VERSION}
    container_name: ${BENTOV2_AUTH_CONTAINER_NAME}
    command: ["-b", "${BENTOV2_AUTH_SERVICE_HOST}", "-Dkeycloak.migration.strategy=IGNORE_EXISTING"]
    ports:
       - "${BENTOV2_AUTH_EXTERNAL_PORT}:${BENTOV2_AUTH_INTERNAL_PORT}"
    environment: 
      - KEYCLOAK_USER=${BENTOV2_AUTH_ADMIN_USER}
      - KEYCLOAK_PASSWORD=${BENTOV2_AUTH_ADMIN_PASSWORD}
    networks:
      - bridge-net
    volumes:
      - ${BENTOV2_AUTH_VOL_DIR}:/opt/jboss/keycloak/standalone/data
      - ${BENTOV2_AUTH_VOL_DIR}/standalone-ha.xml:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml


  web:
    build:
      context: $PWD/lib/web
      args:
        BASE_IMAGE: ${BENTOV2_WEB_BASE_IMAGE}
        BASE_IMAGE_VERSION: ${BENTOV2_WEB_BASE_IMAGE_VERSION}
        BENTO_WEB_REPO: ${BENTO_WEB_REPO}
        BENTO_WEB_BRANCH: ${BENTO_WEB_BRANCH}
    image: ${BENTOV2_WEB_IMAGE}:${BENTOV2_WEB_VERSION}
    container_name: ${BENTOV2_WEB_CONTAINER_NAME}
    networks: 
      - bridge-net
    ports:
       - "${BENTOV2_WEB_EXTERNAL_PORT}:${BENTOV2_WEB_INTERNAL_PORT}"


  katsu:
    build:
      context: $PWD/lib/katsu
      args:
        BASE_IMAGE:  ${BENTOV2_KATSU_BASE_IMAGE}
        BASE_IMAGE_VERSION: ${BENTOV2_KATSU_BASE_IMAGE_VERSION}
        KATSU_REPO: ${KATSU_REPO}
        KATSU_BRANCH: ${KATSU_BRANCH}
        KATSU_TAG: ${KATSU_TAG}
    image: ${BENTOV2_KATSU_IMAGE}:${BENTOV2_KATSU_VERSION}
    container_name: ${BENTOV2_KATSU_CONTAINER_NAME}
    ports:
      - "${BENTOV2_KATSU_EXTERNAL_PORT}:${BENTOV2_KATSU_INTERNAL_PORT}"
    networks: 
      - bridge-net
    depends_on:
      - katsu-db
    environment:
      - CHORD_URL=${CHORD_METADATA_HOST}
      - CHORD_PERMISSIONS="${CHORD_METADATA_AUTH}"
      - CHORD_DEBUG="${CHORD_METADATA_DEBUG}"
      - POSTGRES_HOST=${BENTOV2_KATSU_DB_CONTAINER_NAME}
      - POSTGRES_USER=${BENTOV2_KATSU_DB_USER}
      - POSTGRES_PASSWORD=${BENTOV2_KATSU_DB_PASSWORD}
    configs:
      - source: chord-metadata-settings
        target: /katsu/metadata/settings.py
        mode: 0644
    secrets:
      - source: metadata-app-secret
        target: metadata_app_secret
      - source: metadata-db-user
        target: metadata_db_user
      - source: metadata-db-secret
        target: metadata_db_secret
    entrypoint:
      - /bin/sh
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:${BENTOV2_KATSU_INTERNAL_PORT}


  katsu-db:
    image: ${BENTOV2_KATSU_DB_IMAGE}:${BENTOV2_KATSU_DB_VERSION}
    container_name: ${BENTOV2_KATSU_DB_CONTAINER_NAME}
    networks: 
      - bridge-net
    environment:
      - POSTGRES_USER=${BENTOV2_KATSU_DB_USER}
      - POSTGRES_PASSWORD=${BENTOV2_KATSU_DB_PASSWORD}
      #- POSTGRES_PASSWORD_FILE="/run/secrets/metadata_db_secret"
      - POSTGRES_DB=${BENTOV2_KATSU_DB}
    # ports: 
    #   - 5432
    secrets:
      - source: metadata-db-user
        target: metadata_db_user
      - source: metadata-db-secret
        target: metadata_db_secret
    volumes: 
      - ${BENTOV2_KATSU_DB_VOL_DIR}:/var/lib/postgresql/data


  drop-box:
    build:
      context: $PWD/lib/drop-box
      args:
        BASE_IMAGE: ${BENTOV2_DROP_BOX_BASE_IMAGE}
        BASE_IMAGE_VERSION: ${BENTOV2_DROP_BOX_BASE_IMAGE_VERSION}
        REPO: ${BENTO_DROP_BOX_REPO}
        BRANCH: ${BENTO_DROP_BOX_BRANCH}
        TAG: ${BENTO_DROP_BOX_TAG}
    image: ${BENTOV2_DROP_BOX_IMAGE}:${BENTOV2_DROP_BOX_VERSION}
    container_name: ${BENTOV2_DROP_BOX_CONTAINER_NAME}
    environment: 
      # Runtime
      - FLASK_DEBUG=False
      - FLASK_APP=bento_drop_box_service.app
      # Storage
      - MINIO_URL=${BENTOV2_DROP_BOX_MINIO_URL}
      - MINIO_USERNAME=${BENTOV2_DROP_BOX_MINIO_USERNAME}
      - MINIO_PASSWORD=${BENTOV2_DROP_BOX_MINIO_PASSWORD}
      - MINIO_BUCKET=${BENTOV2_DROP_BOX_MINIO_BUCKET}
    networks: 
      - bridge-net
    ports:
       - "${BENTOV2_DROP_BOX_EXTERNAL_PORT}:${BENTOV2_DROP_BOX_INTERNAL_PORT}"


  service-registry:
    build:
      context: $PWD/lib/service-registry
      args:
        BASE_IMAGE: ${BENTOV2_SERVICE_REGISTRY_BASE_IMAGE}
        BASE_IMAGE_VERSION: ${BENTOV2_SERVICE_REGISTRY_BASE_IMAGE_VERSION}
        REPO: ${BENTO_SERVICE_REGISTRY_REPO}
        BRANCH: ${BENTO_SERVICE_REGISTRY_BRANCH}
        TAG: ${BENTO_SERVICE_REGISTRY_TAG}
    image: ${BENTOV2_SERVICE_REGISTRY_IMAGE}:${BENTOV2_SERVICE_REGISTRY_VERSION}
    container_name: ${BENTOV2_SERVICE_REGISTRY_CONTAINER_NAME}
    environment: 
      # Runtime
      - FLASK_DEBUG=False
      - FLASK_APP=bento_service_registry.app

      # Following the chord_services.json schema
      # (https://github.com/c3g/chord_singularity/blob/master/chord_services.schema.json)
      # A list of services on a single domain which are registered in the service
      # registry instance.
      - CHORD_SERVICES=chord_services.json

      # Common URL base for all services
      - CHORD_URL=${BENTOV2_PUBLIC_URL}

      # Timeout, in seconds (integers only), for contacting services from the JSON
      - CONTACT_TIMEOUT=1

      # Service ID for the /service-info endpoint
      - SERVICE_ID=ca.c3g.bento:${BENTOV2_SERVICE_REGISTRY_VERSION}

      # Python path template for the services, off of the CHORD_URL value
      # Currently only supports artifact-based paths
      - URL_PATH_FORMAT=api/{artifact}
    networks: 
      - bridge-net
    ports:
       - "${BENTOV2_SERVICE_REGISTRY_EXTERNAL_PORT}:${BENTOV2_SERVICE_REGISTRY_INTERNAL_PORT}"


  logging:
    build:
      context: $PWD/lib/logging
      args:
        BASE_IMAGE: ${BENTOV2_LOGGING_BASE_IMAGE}
        BASE_IMAGE_VERSION: ${BENTOV2_LOGGING_BASE_IMAGE_VERSION}
        REPO: ${BENTO_LOGGING_REPO}
        BRANCH: ${BENTO_LOGGING_BRANCH}
        TAG: ${BENTO_LOGGING_TAG}
    image: ${BENTOV2_LOGGING_IMAGE}:${BENTOV2_LOGGING_VERSION}
    container_name: ${BENTOV2_LOGGING_CONTAINER_NAME}
    environment: 
      # Runtime
      - FLASK_DEBUG=False
      - FLASK_APP=app
    networks: 
      - bridge-net
    ports:
       - "${BENTOV2_LOGGING_EXTERNAL_PORT}:${BENTOV2_LOGGING_INTERNAL_PORT}"


  drs:
    build:
      context: $PWD/lib/drs
      args:
        BASE_IMAGE: ${BENTOV2_DRS_BASE_IMAGE}
        BASE_IMAGE_VERSION: ${BENTOV2_DRS_BASE_IMAGE_VERSION}
        REPO: ${BENTO_DRS_REPO}
        BRANCH: ${BENTO_DRS_BRANCH}
        TAG: ${BENTO_DRS_TAG}
    image: ${BENTOV2_DRS_IMAGE}:${BENTOV2_DRS_VERSION}
    container_name: ${BENTOV2_DRS_CONTAINER_NAME}
    environment: 
      # Runtime
      - FLASK_DEBUG=False
      - FLASK_APP=app
    networks: 
      - bridge-net
    ports:
       - "${BENTOV2_DRS_EXTERNAL_PORT}:${BENTOV2_DRS_INTERNAL_PORT}"


  variant:
    build:
      context: $PWD/lib/variant
      args:
        BASE_IMAGE: ${BENTOV2_VARIANT_BASE_IMAGE}
        BASE_IMAGE_VERSION: ${BENTOV2_VARIANT_BASE_IMAGE_VERSION}
        REPO: ${BENTO_VARIANT_REPO}
        BRANCH: ${BENTO_VARIANT_BRANCH}
        TAG: ${BENTO_VARIANT_TAG}
    image: ${BENTOV2_VARIANT_IMAGE}:${BENTOV2_VARIANT_VERSION}
    container_name: ${BENTOV2_VARIANT_CONTAINER_NAME}
    environment: 
      - FLASK_DEBUG=False
      - FLASK_APP=app

      - TABLE_MANAGER=${BENTOV2_VARIANT_TABLE_MANAGER}
      - DRS_URL_BASE_PATH=${BENTOV2_VARIANT_DRS_URL_BASE_PATH}
      - SERVICE_ID=${BENTOV2_VARIANT_SERVICE_ID}
      - INITIALIZE_IMMEDIATELY=${BENTOV2_VARIANT_INITIALIZE_IMMEDIATELY}
      - DATA=${BENTOV2_VARIANT_DATA}
      - CHORD_URL=${BENTOV2_VARIANT_CHORD_URL}

    networks: 
      - bridge-net
    ports:
       - "${BENTOV2_VARIANT_EXTERNAL_PORT}:${BENTOV2_VARIANT_INTERNAL_PORT}"


  notification:
    build:
      context: $PWD/lib/notification
      args:
        BASE_IMAGE: ${BENTOV2_NOTIFICATION_BASE_IMAGE}
        BASE_IMAGE_VERSION: ${BENTOV2_NOTIFICATION_BASE_IMAGE_VERSION}
        REPO: ${BENTO_NOTIFICATION_REPO}
        BRANCH: ${BENTO_NOTIFICATION_BRANCH}
        TAG: ${BENTO_NOTIFICATION_TAG}
    image: ${BENTOV2_NOTIFICATION_IMAGE}:${BENTOV2_NOTIFICATION_VERSION}
    container_name: ${BENTOV2_NOTIFICATION_CONTAINER_NAME}
    environment: 
      - FLASK_DEBUG=False
      - FLASK_APP=app
      - DATABASE=/notification/data
      - REDIS_HOST=${BENTOV2_REDIS_CONTAINER_NAME}
      - REDIS_PORT=${BENTOV2_REDIS_INTERNAL_PORT}
    networks: 
      - bridge-net
    ports:
       - ${BENTOV2_NOTIFICATION_EXTERNAL_PORT}:${BENTOV2_NOTIFICATION_INTERNAL_PORT}
    volumes:
      - ${BENTOV2_NOTIFICATION_VOL_DIR}:/notification/data



  federation:
    build:
      context: $PWD/lib/federation
      args:
        BASE_IMAGE: ${BENTOV2_FEDERATION_BASE_IMAGE}
        BASE_IMAGE_VERSION: ${BENTOV2_FEDERATION_BASE_IMAGE_VERSION}
        REPO: ${BENTO_FEDERATION_REPO}
        BRANCH: ${BENTO_FEDERATION_BRANCH}
        TAG: ${BENTO_FEDERATION_TAG}
    image: ${BENTOV2_FEDERATION_IMAGE}:${BENTOV2_FEDERATION_VERSION}
    container_name: ${BENTOV2_FEDERATION_CONTAINER_NAME}
    environment: 
      - DATABASE=/federation/data/federation.db
      - INITIALIZE_IMMEDIATELY=false
      - CHORD_DEBUG=false
      - BENTO_FEDERATION_MODE=true
      - CHORD_URL=${BENTOV2_PUBLIC_URL}
      - CHORD_REGISTRY_URL=${BENTOV2_PUBLIC_URL}
      - OIDC_DISCOVERY_URI=${BENTOV2_AUTH_PUBLIC_URL}/auth/realms/${BENTOV2_AUTH_REALM}/.well-known/openid-configuration
      # PORT: Specified when running via ./run.py; defaults to 5000
      # SERVICE_URL_BASE_PATH: Base URL fragment (e.g. /test/) for endpoints
      # SOCKET: Specifies Unix socket location for production deployment

    networks: 
      - bridge-net
    ports:
       - ${BENTOV2_FEDERATION_EXTERNAL_PORT}:${BENTOV2_FEDERATION_INTERNAL_PORT}
    volumes:
      - ${BENTOV2_FEDERATION_VOL_DIR}:/federation/data


  event-relay:
    build:
      context: $PWD/lib/event-relay
      args:
        BASE_IMAGE: ${BENTOV2_EVENT_RELAY_BASE_IMAGE}
        BASE_IMAGE_VERSION: ${BENTOV2_EVENT_RELAY_BASE_IMAGE_VERSION}
        REPO: ${BENTO_EVENT_RELAY_REPO}
        BRANCH: ${BENTO_EVENT_RELAY_BRANCH}
        TAG: ${BENTO_EVENT_RELAY_TAG}
    image: ${BENTOV2_EVENT_RELAY_IMAGE}:${BENTOV2_EVENT_RELAY_VERSION}
    container_name: ${BENTOV2_EVENT_RELAY_CONTAINER_NAME}
    environment: 
      # If true, JSON_MESSAGES will parse all messages recieved from the subscription
      # and de-serialize them before passing them to the socket.io connection.
      # e.g. If the message {"test": true} is passed with JSON_MESSAGES on, the
      # corresponding socket.io message will be:
      # {"message": {"test": true}, "channel": "chord.something"}
      # Otherwise, the message will be:
      # {"message": "{\"test\": true}", "channel": "chord.something"}
      - JSON_MESSAGES="true" 

      # Default: blank, base path for the service-info endpoint
      # If blank, the service-info endpoint will be mounted on /service-info
      # If e.g. /base, the endpoint will be mounted on /base/service-info
      #- SERVICE_URL_BASE_PATH=

      # socket.io "path" for the server created by the service.
      - SOCKET_IO_PATH="/socket.io"

      # Connection string (URL or path to UNIX socket file) for the Redis instance.
      - REDIS_CONNECTION=redis://${BENTOV2_REDIS_CONTAINER_NAME}:${BENTOV2_REDIS_INTERNAL_PORT}

      # Subscription pattern the Redis PubSub connection. The default is configured
      # to be chord.* for the Bento platform, but it can be set to anything.
      # See https://redis.io/topics/pubsub and specifically the pattern-matching.
      - REDIS_SUBSCRIBE_PATTERN="chord.*"

      # Where the service will listen for requests. Can be a UNIX socket path or a
      # port number (e.g. 8080, which is the default value if nothing is set.)
      # Will also check the SERVICE_SOCKET environment variable for legacy reasons
      # related to the Bento platform.
      #- SERVICE_LISTEN_ON="/path/to/event_relay.sock"
    networks: 
      - bridge-net
    ports:
       - ${BENTOV2_EVENT_RELAY_EXTERNAL_PORT}:${BENTOV2_EVENT_RELAY_INTERNAL_PORT}


  wes:
    build:
      context: $PWD/lib/wes
      args:
        BASE_IMAGE: ${BENTOV2_WES_BASE_IMAGE}
        BASE_IMAGE_VERSION: ${BENTOV2_WES_BASE_IMAGE_VERSION}
        REPO: ${BENTO_WES_REPO}
        BRANCH: ${BENTO_WES_BRANCH}
        TAG: ${BENTO_WES_TAG}
    image: ${BENTOV2_WES_IMAGE}:${BENTOV2_WES_VERSION}
    container_name: ${BENTOV2_WES_CONTAINER_NAME}
    environment: 
      - CHORD_SERVICES=/wes/chord_services.json
      - CHORD_URL=${BENTOV2_PUBLIC_URL}
      - CELERY_RESULT_BACKEND=redis://${BENTOV2_REDIS_CONTAINER_NAME}:${BENTOV2_REDIS_INTERNAL_PORT}
      - CELERY_BROKER_URL=redis://${BENTOV2_REDIS_CONTAINER_NAME}:${BENTOV2_REDIS_INTERNAL_PORT}
      - DATABASE=bento_wes.db
      - SERVICE_ID=
      - SERVICE_TEMP=tmp
      - SERVICE_URL_BASE_PATH=/
      - WOM_TOOL_LOCATION=/wes/womtool.jar
      - WRITE_OUTPUT_TO_DRS=False
      - DRS_DEDUPLICATE=True
      - DRS_SKIP_TYPES=
    networks: 
      - bridge-net
    ports:
       - ${BENTOV2_WES_EXTERNAL_PORT}:${BENTOV2_WES_INTERNAL_PORT}


  redis:
    image: ${BENTOV2_REDIS_BASE_IMAGE}:${BENTOV2_REDIS_BASE_IMAGE_VERSION}
    container_name: ${BENTOV2_REDIS_CONTAINER_NAME}
    networks: 
      - bridge-net
    ports:
       - ${BENTOV2_REDIS_EXTERNAL_PORT}:${BENTOV2_REDIS_INTERNAL_PORT}
       

networks: 
  bridge-net:
    external: true