version: '3.7'

secrets:
  metadata-app-secret:
    file: $PWD/tmp/secrets/metadata-app-secret
  metadata-db-user:
    file: $PWD/tmp/secrets/metadata-db-user
  metadata-db-secret:
    file: $PWD/tmp/secrets/metadata-db-secret

services:
  web:
    build:
      args:
        BENTO_WEB_IS_DEBUG: "true"
        BENTO_WEB_USER: ${CURRENT_UID}
    volumes:
      - ./lib/web/bento_web:/web/bento_web
    # Execute npm build/install and watch, and 
    # nginx "listener" upon container startup
    entrypoint: sh /web/dev_startup.sh
    extends:
      file: docker-compose.yaml
      service: web

  variant:
    build:
      context: $PWD/lib/variant
      dockerfile: Dockerfile.dev
    extends:
      file: docker-compose.yaml
      service: variant
    command: >
      sh -c  "ls -lah &&
              cd bento_variant_service/bento_variant_service &&
              ls -lah &&
              flask run --host=0.0.0.0"
    volumes: 
      - ./lib/variant/bento_variant_service:/variant/bento_variant_service/bento_variant_service
      - ${BENTOV2_VARIANT_VOL_DIR}:${BENTOV2_VARIANT_DATA}
      - ${BENTOV2_DRS_VOL_DIR}:/drs/chord_drs/data

  gateway:
    # Override network aliases, adding BENTOV2_AUTH_DOMAIN
    networks: 
        bridge-net:
          aliases:
            - ${BENTOV2_DOMAIN}
            - ${BENTOV2_PORTAL_DOMAIN}
            - ${BENTOV2_AUTH_DOMAIN}
    extends:
      file: docker-compose.yaml
      service: gateway

  katsu:
    build:
      context: $PWD/lib/katsu
      dockerfile: Dockerfile.dev
    networks: 
      - bridge-net
    depends_on:
      - katsu-db
    extends:
      file: $PWD/lib/katsu/docker-compose.katsu.yaml
      service: katsu
    volumes: 
      - ./lib/katsu/katsu:/app/katsu

  katsu-db:
    networks: 
      - bridge-net
    extends:
      file: $PWD/lib/katsu/docker-compose.katsu.yaml
      service: katsu-db

  wes:
    build:
      context: $PWD/lib/wes
      dockerfile: Dockerfile.dev
    networks: 
      - bridge-net
    extends:
      file: $PWD/lib/wes/docker-compose.wes.yaml
      service: wes
    volumes: 
      - ./lib/wes/bento_wes:/wes/bento_wes
    ports:
      - "5000:5000"

networks: 
  bridge-net:
    external: true