version: '3.7'


secrets:
  metadata-app-secret:
    file: $PWD/tmp/secrets/metadata-app-secret
  metadata-db-user:
    file: $PWD/tmp/secrets/metadata-db-user
  metadata-db-secret:
    file: $PWD/tmp/secrets/metadata-db-secret


services:
  ingress:
    build:
      context: $PWD/lib/ingress
      args:
        BASE_IMAGE: openresty/openresty #nginx
        BASE_IMAGE_VERSION: alpine-fat #1.19.6-alpine
    image: bentov2-ingress:0.0.1
    container_name: bentov2-ingress
    networks: 
      - bridge-net
    ports:
      - "80:80"
      - "443:443"
    # volumes: 
    #   - $PWD/lib/ingress/nginx.conf:/etc/nginx/nginx.conf


  web:
    build:
      context: $PWD/lib/web
      args:
        BASE_IMAGE: node
        BASE_IMAGE_VERSION: 15.5.1-alpine3.10
        BENTO_WEB_REPO: ${BENTO_WEB_REPO}
        BENTO_WEB_BRANCH: ${BENTO_WEB_BRANCH}
    image: ${BENTOV2_WEB_IMAGE}:${BENTOV2_WEB_VERSION}
    container_name: ${BENTOV2_WEB_CONTAINER_NAME}
    networks: 
      - bridge-net
    ports:
       - "${BENTOV2_WEB_EXTERNAL_PORT}:${BENTOV2_WEB_INTERNAL_PORT}"
    environment:
      - INTERNAL_PORT=${BENTOV2_WEB_INTERNAL_PORT}


  katsu:
    build:
      context: $PWD/lib/katsu
      args:
        BASE_IMAGE:  python
        BASE_IMAGE_VERSION: 3.6-alpine
        KATSU_REPO: ${KATSU_REPO}
        KATSU_BRANCH: ${KATSU_BRANCH}
        KATSU_TAG: ${KATSU_TAG}
    image: ${BENTOV2_KATSU_IMAGE}:${BENTOV2_KATSU_VERSION}
    container_name: bentov2-katsu
    ports:
      - "${BENTOV2_KATSU_INTERNAL_PORT}:${BENTOV2_KATSU_EXTERNAL_PORT}"
    networks: 
      - bridge-net
    depends_on:
      - katsu-db
    environment:
      - CHORD_URL="${CHORD_METADATA_HOST}"
      - CHORD_PERMISSIONS="${CHORD_METADATA_AUTH}"
      - CHORD_DEBUG="${CHORD_METADATA_DEBUG}"
      - POSTGRES_HOST=bentov2-katsu-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=devpassword123
    configs:
      - source: chord-metadata-settings
        target: /katsu/metadata/settings.py
        mode: 0644
    secrets:
      - source: metadata-app-secret
        target: metadata_app_secret
      - source: metadata-db-user
        target: metadata_db_user
      - source: metadata-db-secret
        target: metadata_db_secret
    entrypoint:
      - /bin/sh
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000


  katsu-db:
    image: postgres:13-alpine
    container_name: bentov2-katsu-db
    networks: 
      - bridge-net
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=devpassword123
      #- POSTGRES_PASSWORD_FILE="/run/secrets/metadata_db_secret"
      - POSTGRES_DB=metadata
    secrets:
      - source: metadata-db-user
        target: metadata_db_user
      - source: metadata-db-secret
        target: metadata_db_secret


networks: 
  bridge-net:
    external: true