services:
  web:
    extends:
      file: docker-compose.yaml
      service: web
    environment:
      - NODE_ENV=production
    volumes:
      - $PWD/lib/web/branding.png:/web/dist/static/branding.png:ro
