version: '3.7'

services:
  web:
    build:
      args:
        BENTO_WEB_IS_DEBUG: "true"
    volumes:
      - ./lib/web/bento_web:/web/bento_web
    # Execute npm build/install and watch, and 
    # nginx "listener" upon container startup
    entrypoint: sh /web/dev_startup.sh
    extends:
      file: docker-compose.yaml
      service: web

networks: 
  bridge-net:
    external: true