version: '3.7'

secrets:
  metadata-app-secret:
    file: $PWD/tmp/secrets/metadata-app-secret
  metadata-db-user:
    file: $PWD/tmp/secrets/metadata-db-user
  metadata-db-secret:
    file: $PWD/tmp/secrets/metadata-db-secret

services:
  web:
    build:
      args:
        BENTO_WEB_IS_DEBUG: "true"
        BENTO_WEB_USER: ${CURRENT_UID}
    volumes:
      - ./lib/web/bento_web:/web/bento_web
    # Execute npm build/install and watch, and
    # nginx "listener" upon container startup
    entrypoint: sh /web/dev_startup.sh
    extends:
      file: docker-compose.yaml
      service: web

  public:
    extends:
      file: ./lib/bento_public/docker-compose.yaml
      service: public
    ports:
      - "${BENTO_PUBLIC_EXTERNAL_PORT}:${BENTO_PUBLIC_INTERNAL_PORT}"


  gateway:
    # Override network aliases, adding BENTOV2_AUTH_DOMAIN
    networks:
        bridge-net:
          aliases:
            - ${BENTOV2_DOMAIN}
            - ${BENTOV2_PORTAL_DOMAIN}
            - ${BENTOV2_AUTH_DOMAIN}
    extends:
      file: docker-compose.yaml
      service: gateway

  katsu:
    build:
      context: $PWD/lib/katsu
      dockerfile: Dockerfile.dev
    networks:
      - bridge-net
    depends_on:
      - katsu-db
    extends:
      file: $PWD/lib/katsu/docker-compose.katsu.yaml
      service: katsu
    volumes:
      - ./lib/katsu/katsu:/app/katsu
      - ${BENTOV2_KATSU_DEV_WES_VOL_TMP_DIR}:/wes/tmp
    environment:
      - CHORD_DEBUG=true
      - DEBUGGER_PORT=${BENTOV2_KATSU_DEBUGGER_EXTERNAL_PORT}
    ports:
      - "${BENTOV2_KATSU_EXTERNAL_PORT}:${BENTOV2_KATSU_INTERNAL_PORT}"
      - "${BENTOV2_KATSU_DEBUGGER_EXTERNAL_PORT}:${BENTOV2_KATSU_DEBUGGER_INTERNAL_PORT}"
    entrypoint:
      - /bin/sh
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver --nothreading 0.0.0.0:${BENTOV2_KATSU_INTERNAL_PORT}

  katsu-db:
    networks:
      - bridge-net
    extends:
      file: $PWD/lib/katsu/docker-compose.katsu.yaml
      service: katsu-db
    ports:
      - "${BENTOV2_KATSU_DB_EXTERNAL_PORT}:${BENTOV2_KATSU_DB_INTERNAL_PORT}"
    volumes:
      - ${BENTOV2_KATSU_DB_DEV_VOL_DIR}:/var/lib/postgresql/data


  federation:
    build:
      context: $PWD/lib/federation
      dockerfile: Dockerfile.dev
    environment:
      - CHORD_DEBUG=${BENTOV2_FEDERATION_DEV_DEBUG}
      - PORT=${BENTOV2_FEDERATION_INTERNAL_PORT}
      - DEBUGGER_PORT=${BENTOV2_FEDERATION_DEBUGGER_INTERNAL_PORT}
    networks:
      - bridge-net
    extends:
      file: $PWD/lib/federation/docker-compose.federation.yaml
      service: federation
    volumes:
      - ./lib/federation/bento_federation_service:/federation/bento_federation_service
    ports:
      - "${BENTOV2_FEDERATION_EXTERNAL_PORT}:${BENTOV2_FEDERATION_INTERNAL_PORT}"
      - "${BENTOV2_FEDERATION_DEBUGGER_EXTERNAL_PORT}:${BENTOV2_FEDERATION_DEBUGGER_INTERNAL_PORT}"
    command: >
      sh -c "python run.py"

  wes:
    build:
      context: $PWD/lib/wes
      dockerfile: Dockerfile.dev
    networks:
      - bridge-net
    environment:
      - CHORD_DEBUG=true
      - DEBUGGER_PORT=${BENTOV2_WES_DEBUGGER_EXTERNAL_PORT}
    extends:
      file: $PWD/lib/wes/docker-compose.wes.yaml
      service: wes
    volumes:
      - ./lib/wes/bento_wes:/wes/bento_wes
      - ${BENTOV2_WES_DEV_VOL_DIR}:/wes/data
      - ${BENTOV2_WES_DEV_VOL_TMP_DIR}:/wes/tmp
      - ${BENTOV2_WES_VOL_CACHE_DIR}:/wes/cache
      - ${BENTOV2_WES_DEV_DROP_BOX_VOL_DIR}:/data
    ports:
      - "${BENTOV2_WES_EXTERNAL_PORT}:${BENTOV2_WES_INTERNAL_PORT}"
      - "${BENTOV2_WES_DEBUGGER_EXTERNAL_PORT}:${BENTOV2_WES_DEBUGGER_INTERNAL_PORT}"

  drs:
    build:
      context: $PWD/lib/drs
      dockerfile: Dockerfile.dev
    environment:
      - FLASK_DEBUG=true
      - DEBUGGER_PORT=${BENTOV2_DRS_DEBUGGER_EXTERNAL_PORT}
    networks:
      - bridge-net
    extends:
      file: $PWD/lib/drs/docker-compose.drs.yaml
      service: drs
    ports:
      - "${BENTOV2_DRS_EXTERNAL_PORT}:5000"
      - "${BENTOV2_DRS_DEBUGGER_EXTERNAL_PORT}:${BENTOV2_DRS_DEBUGGER_INTERNAL_PORT}"
    volumes:
      - ./lib/drs/bento_drs:/drs/bento_drs
      - ./lib/drs/startup.sh:/drs/bento_drs/chord_drs/startup.sh:ro
      # Override main drs data directory
      - ${BENTOV2_DRS_DEV_VOL_DIR}:/drs/bento_drs/data
      - ${BENTOV2_DRS_DEV_WES_VOL_DIR}:/wes/tmp
    command: >
      sh -c /drs/bento_drs/chord_drs/startup.sh

networks:
  bridge-net:
    external: true