ARG BASE_IMAGE
ARG BASE_IMAGE_VERSION

FROM "${BASE_IMAGE}:${BASE_IMAGE_VERSION}"

# TODO: change USER
USER root

RUN mkdir /drs && \
    mkdir /wes;

RUN echo "Building DRS in Development Mode";

RUN mkdir -p /drs/bento_drs/data/obj && \
    mkdir -p /drs/bento_drs/data/db;

WORKDIR /drs/bento_drs

# Remove comment if custom requirements are needed
COPY ./bento_drs/requirements.txt ./requirements.txt

RUN ["pip", "install", "debugpy", "-r", "requirements.txt"]

WORKDIR /drs/bento_drs/chord_drs
