ARG BASE_IMAGE
ARG BASE_IMAGE_VERSION

FROM "${BASE_IMAGE}:${BASE_IMAGE_VERSION}"

# TODO: change USER
USER root

RUN mkdir /drs && \
    mkdir /wes;

WORKDIR /drs

ARG REPO
ARG BRANCH
ARG TAG

ARG PROJECT_DIRECTORY

RUN echo "Building DRS in Development Mode";

WORKDIR /drs/bento_drs

RUN mkdir -p /drs/bento_drs/data/obj && \
    mkdir -p /drs/bento_drs/data/db;

# Remove comment if custom requirements are needed
COPY ./bento_drs/requirements.txt ./requirements.txt

RUN ["pip", "install", "-r", "requirements.txt"]

WORKDIR /drs/bento_drs/chord_drs
