# ARG BASE_IMAGE
# ARG BASE_IMAGE_VERSION

# debian image
FROM python:3.6-slim-bullseye


ARG BEACON

# TODO: change USER
USER root

RUN apt-get update; \
	apt-get upgrade; \
	apt-get install -y \
		git \
		curl 


RUN mkdir /beacon

# copy config files 
COPY ./config/beacon_service_info.json /beacon/bento_beacon/bento_beacon/config_files/beacon_service_info.json

COPY ./bento_beacon/requirements.txt /beacon/bento_beacon/requirements.txt

# shared volume with local repo, see docker.compose.dev.yaml
WORKDIR /beacon/bento_beacon

RUN pip install debugpy -r requirements.txt; 

WORKDIR /beacon/bento_beacon/bento_beacon
