ARG BASE_IMAGE
ARG BASE_IMAGE_VERSION

FROM "${BASE_IMAGE}:${BASE_IMAGE_VERSION}"

# TODO: change
USER root

RUN mkdir /drop-box
WORKDIR /drop-box

ARG REPO
ARG BRANCH
ARG TAG

#RUN git clone --depth 1 -b "${TAG:-$BRANCH}" "${REPO}" && \
#    ls /drop-box;

RUN echo "Building drop-box in Development Mode";

COPY ./bento_drop_box_service/requirements.txt /drop-box/bento_drop_box_service/requirements.txt 

WORKDIR /drop-box/bento_drop_box_service

RUN pip install -r requirements.txt

WORKDIR /drop-box/bento_drop_box_service
