{
  "CHORD_DEBUG": false,
  "CHORD_PERMISSIONS": true,
  "CHORD_PRIVATE_MODE": ${BENTOV2_PRIVATE_MODE},
  "BENTO_FEDERATION_MODE": true,
  "BENTO_FRONTEND_REPOSITORY": "${BENTO_WEB_REPO}.git",
  "BENTO_FRONTEND_VERSION": "${BENTO_WEB_BRANCH}",
  "CHORD_URL": "${BENTOV2_PUBLIC_URL_TRAILING_SLASH}",
  "CHORD_REGISTRY_URL": "${BENTOV2_PUBLIC_URL}",
  "LISTEN_ON": "unix:/chord/tmp/nginx.sock"
}
