name: Lint
on:
  push:
    paths:
      - '**.py'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        name: Set up Python
        with:
          python-version: "3.10"
      - name: Install flake8
        run: python -m pip install flake8
      - name: Run linter
        run: flake8 --config py_bentoctl/tox.ini py_bentoctl/
