name: Lint
on:
  push:
    paths:
      - "./py_bentoctl"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        name: Set up Python
        with:
          python-version: "3.10.9"
      - name: Install flake8
        run: python -m pip install flake8
      - name: Run linter
        run: flake8 ./py_bentoctl
