name: Lint
on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
jobs:
  py-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        name: Setup python
        with:
          python-version: "3.10"
      - name: Install flake8
        run: python -m pip install flake8
      - name: Run lint on py_bentoctl module
        run: flake8 ./py_bentoctl