name: push-actions
on: [push]
jobs:
  check-push-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Gather variables
        id: envx
        uses: docker/setup-buildx-action@v1
        run: source .env

      - name: Build & Run Web
        id: webx
        run: make run-web