ARG BASE_IMAGE
ARG BASE_IMAGE_VERSION

FROM "${BASE_IMAGE}:${BASE_IMAGE_VERSION}"

# TODO: change USER
USER root

RUN mkdir -p /service-registry/bento_service_registry
WORKDIR /service-registry/bento_service_registry

ARG REPO
ARG BRANCH
ARG TAG

#RUN git clone --depth 1 -b "${TAG:-$BRANCH}" "${REPO}" && \
#    ls /service-registry

# Copy the repo requirements.txt and install them
# directly in the container before loading the project
# directory as a volume


RUN echo "Building Service-registry in Development Mode";

COPY ./bento_service_registry/requirements.txt /service-registry/bento_service_registry/requirements.txt

RUN ["pip", "install", "debugpy", "-r", "requirements.txt"]

# Run
WORKDIR /service-registry

COPY ./gunicorn_starter.sh .
RUN chmod 775 ./gunicorn_starter.sh

#CMD [ "./gunicorn_starter.sh" ]
